name: CI/CD Pipeline Credit Scoring

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-train-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Ambil kode dari repo
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Setup Python
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      # 3. Install Dependensi
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow==2.19.0 scikit-learn pandas numpy matplotlib seaborn dagshub virtualenv

      # 4. Jalankan Training (MLflow Project)
      # Pass secret dari GitHub ke environment variable script
      - name: Run MLflow Project (Training)
        env:
          DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          cd credit_scoring_project
          python modelling.py

      # 5. Baca Run ID yang dihasilkan script tadi
      - name: Get Run ID
        id: get_run_id
        run: |
          cd credit_scoring_project
          run_id=$(cat run_id.txt)
          echo "RUN_ID=$run_id" >> $GITHUB_ENV
          echo "Detected Run ID: $run_id"

      # 6. Login ke Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 7. Build Docker Image dari Model MLflow
      # Syarat ADVANCED: Membuat image langsung dari model hasil training
      - name: Build Docker Image using MLflow
        env:
          MLFLOW_TRACKING_URI: https://dagshub.com/${{ secrets.DAGSHUB_USERNAME }}/Eksperimen_SML_Maulana-Seno-Aji-Yudhantara.mlflow
          MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          mlflow models build-docker \
            --model-uri "runs:/${{ env.RUN_ID }}/random_forest_model" \
            --name "${{ secrets.DOCKER_USERNAME }}/credit-scoring-model:latest" 

      # 8. Push Image ke Docker Hub
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/credit-scoring-model:latest